### ISSUE TITLE
404 error during download. 

### ISSUE THREAD

**Issue by yoanhg421** [GOG-Games-com/GG-Downloader-Windows#7]
First time I get this error, so not sure, I tried redownloading but I remembered the verify and skip is not yet implemented. 

Could be a glitch in the CDN maybe? It downloads fine on the browser.

Game files downloaded fine. just the patch throws the error at this time.

So I skipped the game files and got the same exception. 
`./gg-downloader d a_plague_tale_requiem --game:false --patches:true --goodies:false`

`
Downloading 0 game files, 0 goodies and 1 patches.
Downloading https://cdn.gog-games.com/patches/a_plague_tale_requiem/patch_a_plague_tale_requiem_20221017_1052_(59553)_to_20221107_1062_(60082).exe
Unhandled exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at gg_downloader.Services.HttpClientDownloadWithProgress.DownloadFileFromHttpResponseMessageWithCrc32(HttpResponseMessage response)
   at gg_downloader.Services.HttpClientDownloadWithProgress.StartDownload()
   at gg_downloader.Program.DownloadGame(String slugOrUrl, String username, String password, String downloadRoot, Boolean noDir, Boolean noVerify, Boolean goodies, Boolean patches, Boolean game)
   at gg_downloader.Program.<>c__DisplayClass4_0.<<Main>b__5>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()`

**Comment by GG-Downloader-Win** [comment]
Which version are you using? The "release", or the latest built from source?  This _should_ have been resolved in the latest source, just not published yet. Let me know.

**Comment by yoanhg421** [comment]
I have the latest version before we merged.  I did see the path file is missing on the SFV. could that be it?

**Comment by GG-Downloader-Win** [comment]
Grab the latest from after #6 merged, and let me know it if still occurs.

**Comment by yoanhg421** [comment]
Yes. It is fixed. I'm sorry, I should have updated the project beforehand.  Thank you.

**Comment by GG-Downloader-Win** [comment]
No worries!
